# version: "3.9"
services:
  syncdbzains_rz:
    build: . # Build from the Dockerfile in the current directory
    container_name: syncdbzains_rz
    restart: always
    volumes:
      - ./source:/app
      - ${PATH_LOGS}:/var/log/app
    ports:
      - "${APP_PORT}:8089"
    networks:
      - sym_network

networks:
  sym_network:
    external: true
